#!/usr/bin/env bun
/**
 * The skill's CLI reference is written from the commander program itself, so a flag cannot be
 * renamed, added or given a new default without the reference agents read changing with it.
 * `bun scripts/sync-skill.ts` rewrites it; `--check` fails instead when it is out of date (tests
 * and the CLI build run that).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildProgram } from "../packages/cli/src/program.ts";

/** Commander resolves from the CLI package, not from here, so its type is taken from the program. */
type Command = ReturnType<typeof buildProgram>;

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const CLI_REFERENCE = join(root, "skills/hunch/references/cli.md");

/** What `hunch <command> --help` prints after the option list: notes and worked examples. */
function afterHelp(cmd: Command): string {
  let text = "";
  cmd.configureOutput({ writeOut: (s: string) => { text += s; }, writeErr: () => {} });
  cmd.outputHelp();
  // Everything after the option lists, minus the global options every command repeats.
  const start = text.lastIndexOf("\nOptions:");
  const rest = start >= 0 ? text.slice(text.indexOf("\n\n", start)) : "";
  return rest.replace(/Global Options:\n(?: {2}.*\n?)*/, "").trim();
}

const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function section(cmd: Command, path: string): string {
  const out = [`## \`${path}\``, "", cmd.description(), ""];
  const args = cmd.registeredArguments;
  if (args.length) {
    out.push("| Argument | Required | Means |", "| --- | --- | --- |");
    for (const a of args) out.push(`| \`${a.name()}${a.variadic ? "..." : ""}\` | ${a.required ? "yes" : "no"} | ${cell(a.description)} |`);
    out.push("");
  }
  const options = cmd.options.filter((o) => o.long !== "--help");
  if (options.length) {
    out.push("| Flag | Default | Means |", "| --- | --- | --- |");
    for (const o of options) {
      const def = o.defaultValue === undefined || o.defaultValue === false || (Array.isArray(o.defaultValue) && !o.defaultValue.length)
        ? (o.negate ? `\`${o.attributeName()}\` on` : "")
        : `\`${Array.isArray(o.defaultValue) ? o.defaultValue.join(",") : String(o.defaultValue)}\``;
      out.push(`| \`${cell(o.flags)}\` | ${def} | ${cell(o.description)}${o.mandatory ? " (required)" : ""} |`);
    }
    out.push("");
  }
  const after = afterHelp(cmd);
  if (after) out.push("```text", after, "```", "");
  return out.join("\n");
}

export function renderCliReference(): string {
  // Defaults that GitHub Actions changes are documented as they are everywhere else.
  const saved = { actions: process.env.GITHUB_ACTIONS, base: process.env.GITHUB_BASE_REF };
  delete process.env.GITHUB_ACTIONS;
  delete process.env.GITHUB_BASE_REF;
  const program = buildProgram();
  if (saved.actions !== undefined) process.env.GITHUB_ACTIONS = saved.actions;
  if (saved.base !== undefined) process.env.GITHUB_BASE_REF = saved.base;
  const parts = [
    "<!-- Generated by scripts/sync-skill.ts from the commander program. Do not edit by hand. -->",
    "",
    "# Hunch CLI reference",
    "",
    "Every command, argument and flag, with its default. Run any of them as `npx -y --min-release-age=0 @kelbie/hunch <command>`.",
    "Unknown flags are refused, and each command lists its own with `--help`.",
    "",
    "| Global flag | Means |",
    "| --- | --- |",
    ...program.options.map((o) => `| \`${cell(o.flags)}\` | ${cell(o.description)} |`),
    "",
  ];
  for (const cmd of program.commands) {
    if (cmd.commands.length) for (const sub of cmd.commands) parts.push(section(sub, `hunch ${cmd.name()} ${sub.name()}`));
    else parts.push(section(cmd, `hunch ${cmd.name()}`));
  }
  return `${parts.join("\n").trimEnd()}\n`;
}

if (import.meta.main) {
  const text = renderCliReference();
  if (process.argv.includes("--check")) {
    let current = "";
    try { current = readFileSync(CLI_REFERENCE, "utf8"); } catch {}
    if (current !== text) {
      console.error("skills/hunch/references/cli.md is out of date. Run `bun scripts/sync-skill.ts`.");
      process.exit(1);
    }
  } else {
    writeFileSync(CLI_REFERENCE, text);
    console.log(`synced ${CLI_REFERENCE} from the commander program`);
  }
}
